### ISSUE TITLE
Will there be a  zenoh-pico rust crate

### ISSUE THREAD

**Issue by wuhanstudio** [eclipse-zenoh/zenoh-pico#99]
### Describe the feature

There is already a rust crate of **Zenoh** here: 

https://crates.io/crates/zenoh

I'm wondering if there will be a rust **zenoh-pico** crate in the future, because this repo demonstrates that it's possible to use pure Rust for ESP32 development.

https://github.com/ivmarkov/rust-esp32-std-demo

It would be interesting to use rust **zenoh-pico** on ESP32, so that we can connet ESP32 to ROS2 via [zenoh-plugin-dds](https://github.com/eclipse-zenoh/zenoh-plugin-dds).

**Comment by cguimaraes** [comment]
Zenoh-Pico in Rust is something that we evaluate from time to time, but for the moment it is not in the short-term roadmap.

The reason lies mostly on the lack of support for Rust by the whole ecosystem. While we have seen Rust for ESP32 development (notice that still many functionalities are not yet ported), other RTOS still rely mostly (or only) on C/C++ not yet providing any Rust port.

Since Zenoh-Pico targets not only ESP-IDF, but also other RTOS like Zephyr, MBedOS, Arduino, NuttX, and others, until the entire ecosystem and the community is fully engaged with Rust, C will continue to be the main language for Zenoh-Pico.

In any case, using Zenoh-Pico you can already connect your ESP32 to ROS2 via the zenoh-plugin-dds.
Check the [following blog post](https://zenoh.io/blog/2021-11-09-ros2-zenoh-pico/) for more information.
